import os, strutils, parseopt, times, streams, sequtils, osproc
import common/[isa, constants, utils]
import compiler/[entropy_engine, lexer, parser, codegen, thue_shuffler]
import runtime/vm

proc calculateFnv1a(filePath: string): uint64 =
  var f = open(filePath, fmRead)
  defer: f.close()
  result = 0xcbf29ce484222325'u64
  var buf = newSeq[uint8](4096)
  while not f.endOfFile:
    let bytesRead = f.readBytes(buf, 0, 4096)
    if bytesRead == 0: break
    for i in 0 ..< bytesRead:
      result = result xor uint64(buf[i])
      result = result * 0x00000100000001B3'u64

proc signBinary(filePath: string) =
  let hashVal = calculateFnv1a(filePath)
  var f = open(filePath, fmAppend)
  defer: f.close()
  var h = hashVal
  for i in 0..7:
    f.write(char(h and 0xFF))
    h = h shr 8
  f.write("ATMX")

type
  Mode = enum modeExe, modeAtb, modeDebug
  CompileOptions = object
    srcFile: string
    outFile: string
    mode: Mode
    payloadDir: string

proc transpileWithAtb(srcFile, atbModule: string): (seq[uint8], seq[string]) =
  echo "[V10] Build Trace: 2026-05-15 00:30"
  let fullAtbPath = getAppDir() / atbModule
  if not fileExists(fullAtbPath):
    echo "[!] Fatal Error: Transpilation module NOT FOUND: ", fullAtbPath
    quit(1)

  echo "[V10] Transpiling ", srcFile, " using ", atbModule, "..."
  let srcContent = readFile(srcFile)

  var vm = initVM(true)

  vm.inputFeed = @[]
  for c in srcContent: vm.inputFeed.add(uint8(ord(c)))

  let atbRaw = readFile(fullAtbPath)
  echo "[Debug] Loaded ATB: ", atbRaw.len, " bytes"

  var code: seq[FheBlock] = @[]
  for b in atbRaw:
    code.add(FheBlock(low: b.uint64, high: 0))

  while code.len < 1024:
    code.add(FheBlock(low: opExit.uint64, high: 0))

  try:
    var runtimeEnginePtr = create(AutonomousMalbolge)
    runtimeEnginePtr[] = constructAuto()

    echo "[Debug] Starting VM Run..."
    vm.run(code, runtimeEnginePtr[], 0'i64, 1024, @[], @[srcFile])
    echo "[Debug] VM Finished at PC: ", vm.pc

    dealloc(runtimeEnginePtr)
  except Exception as e:
    echo "[!] Transpilation Failed: ", e.msg
    quit(1)

  echo "[+] Transpilation successful. Generated bytes: ", vm.captureBuffer.len
  return (vm.captureBuffer, @["Transpiled from " & srcFile])

proc showUsage() =
  echo "GuiltyAtomeis V11 Compiler"
  echo "Usage: atmc <source> <output> [options]"
  echo "Options:"
  echo "  --debug    Disable security features for debugging"
  echo "  --atb      Output ATB bytecode only"
  echo "  --dir      Payload output directory (default: current dir)"

proc parseArgs(): CompileOptions =
  var p = initOptParser()
  result.mode = modeExe
  result.payloadDir = getCurrentDir()
  while true:
    p.next()
    case p.kind
    of cmdEnd: break
    of cmdShortOption, cmdLongOption:
      case p.key
      of "debug": result.mode = modeDebug
      of "atb": result.mode = modeAtb
      of "dir": result.payloadDir = p.val
      else: discard
    of cmdArgument:
      if result.srcFile == "": result.srcFile = p.key
      elif result.outFile == "": result.outFile = p.key

  if result.srcFile == "":
    showUsage()
    quit(1)

proc compileSrc(opts: CompileOptions): tuple[bytecode: seq[uint8], pool: seq[string], externs: seq[string]] =
  if opts.srcFile.endsWith(".py"):
    let (bc, pool) = transpileWithAtb(opts.srcFile, "python_trans.atb")
    return (bc, pool, @[])

  let input = readFile(opts.srcFile)
  var tokens = tokenize(input)
  var p = Parser(tokens: tokens, pos: 0)
  let ast = p.parseProgram()
  return generateProgram(ast)

proc buildSingleBinary(opts: CompileOptions, bytecode: seq[uint8],
                       pool: seq[string], withSecurity: bool) =
  let seed: int64 = if withSecurity: cast[int64](getTime().toUnix()) else: 0
  let effectiveSeed: int64 = seed

  var bytecodeEnc: seq[uint8] = @[]
  var buildEngine = constructAuto()
  buildEngine.setRegister(effectiveSeed)

  var thueEngine: ThueShuffler
  if withSecurity:
    let thueSeed = ThueSeed(uint64(effectiveSeed)) + 0x9E3779B9'u64
    thueEngine = initThueShuffler(thueSeed)

  for i in 0 ..< bytecode.len:
    let byteVal = if withSecurity:
      let shuffled = thueEngine.encodeOp(bytecode[i])
      thueEngine.applyStep()
      shuffled
    else:
      bytecode[i]
    if withSecurity:
      let enc = buildEngine.stableEncrypt(byteVal.int32, i)
      bytecodeEnc.add(uint8(enc.low and 0xFF))
      bytecodeEnc.add(uint8((enc.low shr 8) and 0xFF))
      bytecodeEnc.add(uint8((enc.low shr 16) and 0xFF))
      bytecodeEnc.add(uint8((enc.low shr 24) and 0xFF))
      bytecodeEnc.add(uint8((enc.low shr 32) and 0xFF))
      bytecodeEnc.add(uint8((enc.low shr 40) and 0xFF))
      bytecodeEnc.add(uint8((enc.low shr 48) and 0xFF))
      bytecodeEnc.add(uint8((enc.low shr 56) and 0xFF))
      bytecodeEnc.add(uint8(enc.high and 0xFF))
      bytecodeEnc.add(uint8((enc.high shr 8) and 0xFF))
      bytecodeEnc.add(uint8((enc.high shr 16) and 0xFF))
      bytecodeEnc.add(uint8((enc.high shr 24) and 0xFF))
      bytecodeEnc.add(uint8((enc.high shr 32) and 0xFF))
      bytecodeEnc.add(uint8((enc.high shr 40) and 0xFF))
      bytecodeEnc.add(uint8((enc.high shr 48) and 0xFF))
      bytecodeEnc.add(uint8((enc.high shr 56) and 0xFF))
    else:
      bytecodeEnc.add(byteVal)

  let secFlag: uint32 = if withSecurity: 0xDEADBEEF'u32 else: 0x00000000'u32
  let dataSize: int64 = bytecodeEnc.len.int64
  let poolBytes = pool.len * 4 + pool.foldl(a + b.len + 4, 0)

  let payloadPath = opts.payloadDir / "atmc_payload.nim"
  var payloadFile = open(payloadPath, fmWrite)

  payloadFile.writeLine("# Auto-generated by GuiltyAtomeis V11 Compiler")
  payloadFile.writeLine("import os, streams, tables")
  payloadFile.writeLine("import common/[isa, constants, utils]")
  payloadFile.writeLine("import compiler/entropy_engine")
  payloadFile.writeLine("import runtime/vm")
  payloadFile.writeLine("")
  payloadFile.writeLine("const")
  payloadFile.writeLine("  bytecodeLen = " & $bytecode.len)
  payloadFile.writeLine("  buildSeed: int64 = " & $effectiveSeed)
  payloadFile.writeLine("  secFlag: uint32 = 0x" & toHex(secFlag) & "'u32")

  payloadFile.writeLine("  poolData = @[")
  for i, s in pool:
    var escaped = s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
    payloadFile.writeLine("    \"" & escaped & "\",")
  payloadFile.writeLine("  ]")

  payloadFile.writeLine("")
  payloadFile.writeLine("  bytecodeData = @[")
  for b in bytecodeEnc:
    payloadFile.writeLine("    0x" & toHex(b.uint8) & ".uint8,")
  payloadFile.writeLine("  ]")
  payloadFile.writeLine("")
  if withSecurity:
    payloadFile.writeLine("proc verifySelfIntegrity(): bool =")
    payloadFile.writeLine("  let exePath = getAppFilename()")
    payloadFile.writeLine("  if not fileExists(exePath): return true")
    payloadFile.writeLine("  try:")
    payloadFile.writeLine("    var f = open(exePath, fmRead)")
    payloadFile.writeLine("    let fileSize = f.getFileSize()")
    payloadFile.writeLine("    if fileSize <= 12: return false")
    payloadFile.writeLine("    let readLimit = fileSize - 12")
    payloadFile.writeLine("    var hashVal = 0xcbf29ce484222325'u64")
    payloadFile.writeLine("    var buf = newSeq[uint8](4096)")
    payloadFile.writeLine("    var totalRead = 0")
    payloadFile.writeLine("    while totalRead < readLimit:")
    payloadFile.writeLine("      let toRead = min(4096, readLimit - totalRead)")
    payloadFile.writeLine("      let bytesRead = f.readBytes(buf, 0, toRead)")
    payloadFile.writeLine("      if bytesRead == 0: break")
    payloadFile.writeLine("      for i in 0 ..< bytesRead:")
    payloadFile.writeLine("        hashVal = hashVal xor uint64(buf[i])")
    payloadFile.writeLine("        hashVal = hashVal * 0x00000100000001B3'u64")
    payloadFile.writeLine("      totalRead += bytesRead")
    payloadFile.writeLine("    var storedHash: uint64 = 0")
    payloadFile.writeLine("    for i in 0..7:")
    payloadFile.writeLine("      storedHash = storedHash or (uint64(f.readChar().ord) shl (i * 8))")
    payloadFile.writeLine("    var magic = \"\"")
    payloadFile.writeLine("    for i in 0..3: magic.add(f.readChar())")
    payloadFile.writeLine("    f.close()")
    payloadFile.writeLine("    return magic == \"ATMX\" and storedHash == hashVal")
    payloadFile.writeLine("  except:")
    payloadFile.writeLine("    return false")
    payloadFile.writeLine("")

  payloadFile.writeLine("proc main() =")
  payloadFile.writeLine("  var code: seq[FheBlock] = @[]")
  if withSecurity:
    payloadFile.writeLine("  var i = 0")
    payloadFile.writeLine("  while i < bytecodeData.len:")
    payloadFile.writeLine("    let low = uint64(bytecodeData[i]) or")
    payloadFile.writeLine("             (uint64(bytecodeData[i+1]) shl 8) or")
    payloadFile.writeLine("             (uint64(bytecodeData[i+2]) shl 16) or")
    payloadFile.writeLine("             (uint64(bytecodeData[i+3]) shl 24) or")
    payloadFile.writeLine("             (uint64(bytecodeData[i+4]) shl 32) or")
    payloadFile.writeLine("             (uint64(bytecodeData[i+5]) shl 40) or")
    payloadFile.writeLine("             (uint64(bytecodeData[i+6]) shl 48) or")
    payloadFile.writeLine("             (uint64(bytecodeData[i+7]) shl 56)")
    payloadFile.writeLine("    let high = uint64(bytecodeData[i+8]) or")
    payloadFile.writeLine("              (uint64(bytecodeData[i+9]) shl 8) or")
    payloadFile.writeLine("              (uint64(bytecodeData[i+10]) shl 16) or")
    payloadFile.writeLine("              (uint64(bytecodeData[i+11]) shl 24) or")
    payloadFile.writeLine("              (uint64(bytecodeData[i+12]) shl 32) or")
    payloadFile.writeLine("              (uint64(bytecodeData[i+13]) shl 40) or")
    payloadFile.writeLine("              (uint64(bytecodeData[i+14]) shl 48) or")
    payloadFile.writeLine("              (uint64(bytecodeData[i+15]) shl 56)")
    payloadFile.writeLine("    code.add(FheBlock(low: low, high: high))")
    payloadFile.writeLine("    i += 16")
  else:
    payloadFile.writeLine("  for b in bytecodeData:")
    payloadFile.writeLine("    code.add(FheBlock(low: uint64(b), high: 0))")

  if withSecurity:
    payloadFile.writeLine("  if not verifySelfIntegrity():")
    payloadFile.writeLine("    var buildEngine = constructAuto()")
    payloadFile.writeLine("    buildEngine.decoy_loop()")
    payloadFile.writeLine("    quit(1)")
    payloadFile.writeLine("  ")

  payloadFile.writeLine("  var vmEngine = initVM(false)")
  payloadFile.writeLine("  var buildEngine = constructAuto()")
  payloadFile.writeLine("  buildEngine.setRegister(buildSeed)")
  if withSecurity:
    payloadFile.writeLine("  if not buildEngine.opaqueVerify():")
    payloadFile.writeLine("    buildEngine.decoy_loop()")
    payloadFile.writeLine("    quit(1)")
    payloadFile.writeLine("  ")
  payloadFile.writeLine("  try:")
  payloadFile.writeLine("    vmEngine.run(code, buildEngine, buildSeed, bytecodeLen, poolData, commandLineParams())")
  payloadFile.writeLine("  except Exception as e:")
  payloadFile.writeLine("    echo \"[!] CRITICAL_EXCEPTION: \", e.msg")
  payloadFile.writeLine("")
  payloadFile.writeLine("when isMainModule: main()")

  payloadFile.close()

  let outPath = opts.outFile
  var nimCmd = "nim cpp -f -o:" & outPath & " -d:release --app:console --path:\"" &
               getAppDir() / "src\" --cincludes:\"" & getAppDir() / "src\" --noNimblePath "
  if outPath.endsWith(".exe"):
    nimCmd.add("-d:mingw --passL:-static ")
  nimCmd.add(payloadPath)
  echo "[+] Building target binary..."
  let exitCode = execCmd(nimCmd)
  if exitCode != 0:
    echo "[!] Build failed with exit code: ", exitCode
    quit(1)
  echo "[+] Binary written: ", outPath
  if withSecurity:
    signBinary(outPath)

proc main() =
  let opts = parseArgs()
  case opts.mode
  of modeAtb:
    let (bytecode, _, _) = compileSrc(opts)
    writeFile(opts.outFile, cast[string](bytecode))
  of modeDebug:
    if opts.srcFile == "" or opts.outFile == "": quit(1)
    let (bytecode, pool, _) = compileSrc(opts)
    buildSingleBinary(opts, bytecode, pool, false)
    echo "[+] EXE written (debug): ", opts.outFile
  of modeExe:
    if opts.srcFile == "" or opts.outFile == "": quit(1)
    let (bytecode, pool, _) = compileSrc(opts)
    buildSingleBinary(opts, bytecode, pool, true)
    echo "[+] EXE written: ", opts.outFile

if isMainModule: main()
