import os, strutils, parseopt, times, streams, tables
import common/[isa, constants, utils]
import compiler/[entropy_engine, lexer, parser, codegen, thue_shuffler]
import runtime/vm

type
  Mode = enum modeExe, modeAtb, modeDebug
  CompileOptions = object
    srcFile: string
    outFile: string
    mode: Mode

# ATBを介したトランスパイル（外部言語パース）
proc transpileWithAtb(srcFile, atbModule: string): (seq[uint8], seq[string]) =
  echo "[V10] Build Trace: 2026-05-15 00:30"
  let fullAtbPath = getAppDir() / atbModule
  if not fileExists(fullAtbPath):
    echo "[!] Fatal Error: Transpilation module NOT FOUND: ", fullAtbPath
    echo "    Please ensure ", atbModule, " is in the same directory as atmc.exe"
    quit(1)
  
  echo "[V10] Transpiling ", srcFile, " using ", atbModule, "..."
  let srcContent = readFile(srcFile)
  
  # 1. VMを初期化 (トランスパイルは特権モードで実行)
  var vm = initVM(true)
  
  # 2. ソースコードを inputFeed に注入
  vm.inputFeed = @[]
  for c in srcContent: vm.inputFeed.add(uint8(ord(c)))
  
  # 3. ATB モジュールをロード
  let atbRaw = readFile(fullAtbPath)
  echo "[Debug] Loaded ATB: ", atbRaw.len, " bytes"
  if atbRaw.len > 0:
    echo "[Debug] First 4 bytes (HEX): ", toHex(atbRaw[0].uint8), " ", toHex(atbRaw[1].uint8)
  
  var code: seq[FheBlock] = @[]
  for b in atbRaw:
    code.add(FheBlock(low: b.uint64, high: 0))
  
  if code.len > 0:
    echo "[Debug] Code[0].low: ", toHex(code[0].low)
  
  # 領域外での無限ループを防ぐため、1024ブロックまで opExit で埋める
  while code.len < 1024:
    code.add(FheBlock(low: opExit.uint64, high: 0))
  
  # 4. 実行
  try:
    var dummyMaps: seq[Table[uint8, string]] = @[]
    
    # Heap allocation to avoid stack overflow
    var runtimeEnginePtr = create(AutonomousMalbolge)
    runtimeEnginePtr[] = constructAuto()
    
    echo "[Debug] Starting VM Run..."
    vm.run(code, runtimeEnginePtr[], 0'i64, 0'u32, 0, dummyMaps, 1024, @[], @[srcFile])
    echo "[Debug] VM Finished at PC: ", vm.pc
    
    # Clean up
    dealloc(runtimeEnginePtr)
  except Exception as e:
    echo "[!] Transpilation Failed: ", e.msg
    quit(1)
  
  echo "[+] Transpilation successful. Generated bytes: ", vm.captureBuffer.len
  return (vm.captureBuffer, @["Transpiled from " & srcFile])

proc showUsage() =
  echo "GuiltyAtomeis V10 Compiler"
  echo "Usage: atmc.exe <source> <output> [options]"
  echo "Options:"
  echo "  --debug    Disable security features for debugging"
  echo "  --atb      Output ATB bytecode only"

proc parseArgs(): CompileOptions =
  var p = initOptParser()
  result.mode = modeExe
  while true:
    p.next()
    case p.kind
    of cmdEnd: break
    of cmdShortOption, cmdLongOption:
      case p.key
      of "debug": result.mode = modeDebug
      of "atb": result.mode = modeAtb
      else: discard
    of cmdArgument:
      if result.srcFile == "": result.srcFile = p.key
      elif result.outFile == "": result.outFile = p.key
  
  if result.srcFile == "":
    showUsage()
    quit(1)

proc compileSrc(opts: CompileOptions): tuple[bytecode: seq[uint8], pool: seq[string]] =
  if opts.srcFile.endsWith(".py"):
    return transpileWithAtb(opts.srcFile, "python_trans.atb")
  
  # Standard Atomeis syntax
  let input = readFile(opts.srcFile)
  var tokens = tokenize(input)
  var p = Parser(tokens: tokens, pos: 0)
  let ast = p.parseProgram()
  return generateProgram(ast)

proc getTextSection(data: string): tuple[offset: int64, size: int64] =
  if data.len < 64: return
  # ELF64
  if data[0] == '\x7F' and data[1] == 'E' and data[2] == 'L' and data[3] == 'F' and data[4] == '\x02':
    var shoff: uint64
    var shentsize: uint16
    var shnum: uint16
    var shstrndx: uint16
    copyMem(shoff.addr, data[0x28].unsafeAddr, sizeof(shoff))
    copyMem(shentsize.addr, data[0x3A].unsafeAddr, sizeof(shentsize))
    copyMem(shnum.addr, data[0x3C].unsafeAddr, sizeof(shnum))
    copyMem(shstrndx.addr, data[0x3E].unsafeAddr, sizeof(shstrndx))
    if shoff == 0 or shentsize < 60'u16 or shnum == 0: return
    let strtabHdrOff = shoff + shstrndx.uint64 * shentsize.uint64
    var strtabShOffset: uint64
    var strtabShSize: uint64
    if strtabHdrOff + 0x28'u64 >= data.len.uint64: return
    copyMem(strtabShOffset.addr, data[strtabHdrOff + 0x18].unsafeAddr, sizeof(strtabShOffset))
    copyMem(strtabShSize.addr, data[strtabHdrOff + 0x20].unsafeAddr, sizeof(strtabShSize))
    for i in 0 ..< int(shnum):
      let shdrOff = shoff + i.uint64 * shentsize.uint64
      if shdrOff + 0x28'u64 >= data.len.uint64: continue
      var shNameIdx: uint32
      var shType: uint32
      var shFlags: uint64
      var shOffset: uint64
      var shSize: uint64
      copyMem(shNameIdx.addr, data[shdrOff].unsafeAddr, sizeof(shNameIdx))
      copyMem(shType.addr, data[shdrOff + 4].unsafeAddr, sizeof(shType))
      copyMem(shFlags.addr, data[shdrOff + 8].unsafeAddr, sizeof(shFlags))
      copyMem(shOffset.addr, data[shdrOff + 0x18].unsafeAddr, sizeof(shOffset))
      copyMem(shSize.addr, data[shdrOff + 0x20].unsafeAddr, sizeof(shSize))
      if shNameIdx < strtabShSize:
        var pos = strtabShOffset + shNameIdx.uint64
        if pos + 5 < data.len.uint64:
          if data[pos] == '.' and data[pos+1] == 't' and data[pos+2] == 'e' and data[pos+3] == 'x' and data[pos+4] == 't':
            return (cast[int64](shOffset), cast[int64](shSize))
    return
  # PE32+ (Windows)
  if data[0] == 'M' and data[1] == 'Z':
    var e_lfanew: int32
    copyMem(e_lfanew.addr, data[0x3C].unsafeAddr, sizeof(e_lfanew))
    if e_lfanew < 0 or e_lfanew + 4 + 20 >= data.len: return
    if data[e_lfanew] != 'P' or data[e_lfanew+1] != 'E': return
    let fileHdr = e_lfanew + 4
    var machine: uint16
    var numSections: uint16
    var optHdrSize: uint16
    copyMem(machine.addr, data[fileHdr].unsafeAddr, sizeof(machine))
    copyMem(numSections.addr, data[fileHdr + 2].unsafeAddr, sizeof(numSections))
    copyMem(optHdrSize.addr, data[fileHdr + 16].unsafeAddr, sizeof(optHdrSize))
    if machine notin {0x8664'u16, 0x14C'u16}: return
    let sectHdr = fileHdr + 20 + optHdrSize.int
    for i in 0 ..< numSections.int:
      let shdr = sectHdr + i * 40
      if shdr + 36 >= data.len: continue
      if data[shdr] == '.' and data[shdr+1] == 't' and data[shdr+2] == 'e' and data[shdr+3] == 'x' and data[shdr+4] == 't':
        var rawSize: uint32
        var rawOffset: uint32
        copyMem(rawSize.addr, data[shdr + 16].unsafeAddr, sizeof(rawSize))
        copyMem(rawOffset.addr, data[shdr + 20].unsafeAddr, sizeof(rawOffset))
        return (cast[int64](rawOffset), cast[int64](rawSize))

# EXE合成
proc synthesizeExe(opts: CompileOptions, bytecode: seq[uint8],
                   pool: seq[string], withSecurity: bool) =
  let stubPath = when defined(windows):
    getAppDir() / "atomeis_runtime.exe"
  else:
    let p = getAppDir() / "atomeis_runtime"
    if fileExists(p): p else: getAppDir() / "atomeis_runtime.exe"
  if not fileExists(stubPath):
    echo "[!] atomeis_runtime not found in: ", getAppDir()
    quit(1)
  let stubData = readFile(stubPath)

  let seed: int64 = cast[int64](getTime().toUnix())
  let effectiveSeed: int64 = if withSecurity: seed else: 0

  # .text section hash
  let (textOffset, textSize) = getTextSection(stubData)
  let textHash = if textSize > 0:
    var textData = newSeq[byte](textSize)
    copyMem(addr textData[0], unsafeAddr stubData[textOffset], textSize)
    computeTextHash(textData)
  else: 0'u32

  var fs = newFileStream(opts.outFile, fmWrite)
  fs.write(stubData)

  # Pool
  let poolStart = fs.getPosition()
  fs.write(pool.len.int32)
  for s in pool:
    var enc = s
    if withSecurity:
      enc = obfuscateString(s, effectiveSeed)
    fs.write(enc.len.int32)
    fs.write(enc)
  let poolSize = fs.getPosition() - poolStart

  # PIT
  let pitStart = fs.getPosition()
  let numPackets = (bytecode.len + 15) div 16
  fs.write(int32(numPackets + 1))
  for i in 0 .. numPackets: fs.write(int32(i * 16))
  let pitSize = fs.getPosition() - pitStart

  # Maps
  let mapStart = fs.getPosition()
  fs.write(int32(numPackets))
  for _ in 1 .. numPackets:
    # 0 entries for each packet
    fs.write(0.int32)
  let mapSize = fs.getPosition() - mapStart

  # Bytecode
  let dataStart = fs.getPosition()
  var buildEngine = constructAuto()
  buildEngine.setRegister(effectiveSeed)

  # Thue ISA Shuffler: 毎命令シャッフル
  var thueEngine: ThueShuffler
  if withSecurity:
    let thueSeed = ThueSeed(uint64(effectiveSeed)) + 0x9E3779B9'u64
    thueEngine = initThueShuffler(thueSeed)

  var writtenBlocks: seq[FheBlock] = @[]
  for i in 0 ..< bytecode.len:
    let byteVal = if withSecurity:
      let shuffled = thueEngine.encodeOp(bytecode[i])
      thueEngine.applyStep()
      shuffled
    else:
      bytecode[i]
    if withSecurity:
      let enc = buildEngine.stableEncrypt(byteVal.int32, i)
      writtenBlocks.add(enc)
      fs.write(enc.low)
      fs.write(enc.high)
    else:
      let blk = FheBlock(low: byteVal.uint64, high: 0)
      writtenBlocks.add(blk)
      fs.write(byteVal.uint64)
      fs.write(0'u64)  # high は 0
  let dataSize = fs.getPosition() - dataStart

  # Security flag
  let secFlag: uint32 = if withSecurity: 0xDEADBEEF'u32 else: 0x00000000'u32
  
  # No license/expiry - all set to 0
  let licLen: int64 = 0
  let expUnix: int64 = 0

  # Structural Footer (Extended: 108 bytes before VERSION_TAG)
  fs.write(licLen)                       # 8 bytes
  fs.write(expUnix)                      # 8 bytes (reserved)
  fs.write(secFlag)                      # 4 bytes
  fs.write(effectiveSeed)                # 8 bytes
  fs.write(dataSize.int64)               # 8 bytes
  fs.write(mapSize.int64)                # 8 bytes
  fs.write(pitSize.int64)                # 8 bytes
  fs.write(poolSize.int64)               # 8 bytes
  fs.write(bytecode.len.int32)           # 4 bytes
  # 全ペイロードデータの完全性ハッシュ（コード+PIT+マップ+プール）
  # 注意: ハッシュに使うプールは元の文字列（非難読化）で、runtimeのstringPoolと同じ内容
  var pitList: seq[int32] = @[]
  for i in 0 .. numPackets: pitList.add(int32(i * 16))
  var emptyMaps: seq[Table[uint8, string]] = @[]
  for _ in 1 .. numPackets: emptyMaps.add(initTable[uint8, string]())
  let hashVal = computeIntegrityHash(writtenBlocks, uint64(effectiveSeed), emptyMaps, pitList, pool)
  let hashVal2 = computeIntegrityHash(writtenBlocks, uint64(effectiveSeed) xor 0xDEADC0DE'u64, emptyMaps, pitList, pool)
  fs.write(hashVal)                      # 4 bytes (hash)
  fs.write(hashVal2)                     # 4 bytes (dual hash)
  # .text section metadata (XOR-encoded hash)
  let textHashEnc = textHash xor 0x7D7D7D7D'u32
  fs.write(textOffset)                   # 8 bytes
  fs.write(textSize)                     # 8 bytes
  fs.write(textHashEnc)                  # 4 bytes (XOR-encoded)
  # Dynamic Layer 4 expected hash (depends on .text hash)
  let layer4Seed = uint64(textHash) xor 0x12345678'u64
  let layer4Expected = computeIntegrityHash(
    @[FheBlock(low: 0x1111111111111111'u64, high: 0x2222222222222222'u64)],
    layer4Seed, @[],
    @[int32(0), int32(1)],
    @["v"]
  )
  let layer4ExpectedEnc = layer4Expected xor 0x5A5A5A5A'u32
  fs.write(layer4ExpectedEnc)            # 4 bytes (XOR-encoded, dynamic)
  fs.write(VERSION_TAG)                  # 8 bytes
  fs.write(0x87654321'u32)              # 4 bytes
  fs.close()

proc main() =
  let opts = parseArgs()
  case opts.mode
  of modeAtb:
    let (bytecode, _) = compileSrc(opts)
    writeFile(opts.outFile, cast[string](bytecode))
  of modeDebug:
    if opts.srcFile == "" or opts.outFile == "": quit(1)
    let (bytecode, pool) = compileSrc(opts)
    synthesizeExe(opts, bytecode, pool, false)
    echo "[+] EXE written (debug): ", opts.outFile
  of modeExe:
    if opts.srcFile == "" or opts.outFile == "": quit(1)
    let (bytecode, pool) = compileSrc(opts)
    synthesizeExe(opts, bytecode, pool, true)
    echo "[+] EXE written: ", opts.outFile

if isMainModule: main()
