import os, strutils, parseopt, times, streams
import common/[isa, constants, utils]
import compiler/[entropy_engine, lexer, parser, codegen, thue_shuffler]
import runtime/vm

type
  Mode = enum modeExe, modeAtb, modeDebug
  CompileOptions = object
    srcFile: string
    outFile: string
    mode: Mode

# ATBを介したトランスパイル（外部言語パース）
proc transpileWithAtb(srcFile, atbModule: string): (seq[uint8], seq[string]) =
  echo "[V10] Build Trace: 2026-05-15 00:30"
  let fullAtbPath = getAppDir() / atbModule
  if not fileExists(fullAtbPath):
    echo "[!] Fatal Error: Transpilation module NOT FOUND: ", fullAtbPath
    echo "    Please ensure ", atbModule, " is in the same directory as atmc.exe"
    quit(1)
  
  echo "[V10] Transpiling ", srcFile, " using ", atbModule, "..."
  let srcContent = readFile(srcFile)
  
  # 1. VMを初期化 (トランスパイルは特権モードで実行)
  var vm = initVM(true)
  
  # 2. ソースコードを inputFeed に注入
  vm.inputFeed = @[]
  for c in srcContent: vm.inputFeed.add(uint8(ord(c)))
  
  # 3. ATB モジュールをロード
  let atbRaw = readFile(fullAtbPath)
  echo "[Debug] Loaded ATB: ", atbRaw.len, " bytes"
  if atbRaw.len > 0:
    echo "[Debug] First 4 bytes (HEX): ", toHex(atbRaw[0].uint8), " ", toHex(atbRaw[1].uint8)
  
  var code: seq[FheBlock] = @[]
  for b in atbRaw:
    code.add(FheBlock(low: b.uint64, high: 0))
  
  if code.len > 0:
    echo "[Debug] Code[0].low: ", toHex(code[0].low)
  
  # 領域外での無限ループを防ぐため、1024ブロックまで opExit で埋める
  while code.len < 1024:
    code.add(FheBlock(low: opExit.uint64, high: 0))
  
  # 4. 実行
  try:
    # Heap allocation to avoid stack overflow
    var runtimeEnginePtr = create(AutonomousMalbolge)
    runtimeEnginePtr[] = constructAuto()
    
    echo "[Debug] Starting VM Run..."
    vm.run(code, runtimeEnginePtr[], 0'i64, 1024, @[], @[srcFile])
    echo "[Debug] VM Finished at PC: ", vm.pc
    
    # Clean up
    dealloc(runtimeEnginePtr)
  except Exception as e:
    echo "[!] Transpilation Failed: ", e.msg
    quit(1)
  
  echo "[+] Transpilation successful. Generated bytes: ", vm.captureBuffer.len
  return (vm.captureBuffer, @["Transpiled from " & srcFile])

proc showUsage() =
  echo "GuiltyAtomeis V10 Compiler"
  echo "Usage: atmc.exe <source> <output> [options]"
  echo "Options:"
  echo "  --debug    Disable security features for debugging"
  echo "  --atb      Output ATB bytecode only"

proc parseArgs(): CompileOptions =
  var p = initOptParser()
  result.mode = modeExe
  while true:
    p.next()
    case p.kind
    of cmdEnd: break
    of cmdShortOption, cmdLongOption:
      case p.key
      of "debug": result.mode = modeDebug
      of "atb": result.mode = modeAtb
      else: discard
    of cmdArgument:
      if result.srcFile == "": result.srcFile = p.key
      elif result.outFile == "": result.outFile = p.key
  
  if result.srcFile == "":
    showUsage()
    quit(1)

proc compileSrc(opts: CompileOptions): tuple[bytecode: seq[uint8], pool: seq[string]] =
  if opts.srcFile.endsWith(".py"):
    return transpileWithAtb(opts.srcFile, "python_trans.atb")
  
  # Standard Atomeis syntax
  let input = readFile(opts.srcFile)
  var tokens = tokenize(input)
  var p = Parser(tokens: tokens, pos: 0)
  let ast = p.parseProgram()
  return generateProgram(ast)

# EXE合成
proc synthesizeExe(opts: CompileOptions, bytecode: seq[uint8],
                   pool: seq[string], withSecurity: bool) =
  let stubPath = when defined(windows):
    getAppDir() / "atomeis_runtime.exe"
  else:
    let p = getAppDir() / "atomeis_runtime"
    if fileExists(p): p else: getAppDir() / "atomeis_runtime.exe"
  if not fileExists(stubPath):
    echo "[!] atomeis_runtime not found in: ", getAppDir()
    quit(1)
  let stubData = readFile(stubPath)

  let seed: int64 = cast[int64](getTime().toUnix())
  let effectiveSeed: int64 = if withSecurity: seed else: 0

  var fs = newFileStream(opts.outFile, fmWrite)
  fs.write(stubData)

  # Pool
  let poolStart = fs.getPosition()
  fs.write(pool.len.int32)
  for s in pool:
    var enc = s
    if withSecurity:
      enc = obfuscateString(s, effectiveSeed)
    fs.write(enc.len.int32)
    fs.write(enc)
  let poolSize = fs.getPosition() - poolStart

  # PIT
  let pitStart = fs.getPosition()
  let numPackets = (bytecode.len + 15) div 16
  fs.write(int32(numPackets + 1))
  for i in 0 .. numPackets: fs.write(int32(i * 16))
  let pitSize = fs.getPosition() - pitStart

  # Maps
  let mapStart = fs.getPosition()
  fs.write(int32(numPackets))
  for _ in 1 .. numPackets:
    # 0 entries for each packet
    fs.write(0.int32)
  let mapSize = fs.getPosition() - mapStart

  # Bytecode
  let dataStart = fs.getPosition()
  var buildEngine = constructAuto()
  buildEngine.setRegister(effectiveSeed)

  # Thue ISA Shuffler: 毎命令シャッフル
  var thueEngine: ThueShuffler
  if withSecurity:
    let thueSeed = ThueSeed(uint64(effectiveSeed)) + 0x9E3779B9'u64
    thueEngine = initThueShuffler(thueSeed)

  for i in 0 ..< bytecode.len:
    let byteVal = if withSecurity:
      let shuffled = thueEngine.encodeOp(bytecode[i])
      thueEngine.applyStep()
      shuffled
    else:
      bytecode[i]
    if withSecurity:
      let enc = buildEngine.stableEncrypt(byteVal.int32, i)
      fs.write(enc.low)
      fs.write(enc.high)
    else:
      fs.write(byteVal.uint64)
      fs.write(0'u64)  # high は 0
  let dataSize = fs.getPosition() - dataStart

  # Security flag
  let secFlag: uint32 = if withSecurity: 0xDEADBEEF'u32 else: 0x00000000'u32
  
  # Footer
  let licLen: int64 = 0
  let expUnix: int64 = 0

  fs.write(licLen)                       # 8 bytes
  fs.write(expUnix)                      # 8 bytes
  fs.write(secFlag)                      # 4 bytes
  fs.write(effectiveSeed)                # 8 bytes
  fs.write(dataSize.int64)               # 8 bytes
  fs.write(mapSize.int64)                # 8 bytes
  fs.write(pitSize.int64)                # 8 bytes
  fs.write(poolSize.int64)               # 8 bytes
  fs.write(bytecode.len.int32)           # 4 bytes
  fs.write(VERSION_TAG)                  # 8 bytes
  fs.write(0x87654321'u32)              # 4 bytes
  fs.close()

proc main() =
  let opts = parseArgs()
  case opts.mode
  of modeAtb:
    let (bytecode, _) = compileSrc(opts)
    writeFile(opts.outFile, cast[string](bytecode))
  of modeDebug:
    if opts.srcFile == "" or opts.outFile == "": quit(1)
    let (bytecode, pool) = compileSrc(opts)
    synthesizeExe(opts, bytecode, pool, false)
    echo "[+] EXE written (debug): ", opts.outFile
  of modeExe:
    if opts.srcFile == "" or opts.outFile == "": quit(1)
    let (bytecode, pool) = compileSrc(opts)
    synthesizeExe(opts, bytecode, pool, true)
    echo "[+] EXE written: ", opts.outFile

if isMainModule: main()
